import React, { useState } from 'react';
import { User, Dumbbell, Users, BookOpen, Target, Calendar, Image, DollarSign, LogOut, Plus, X, Check, ChevronRight, Star, Clock, Edit, Trash2, Send, Award, Heart, TrendingUp, Minus, CheckCircle } from 'lucide-react';

const CLIENTS = [
  { id: 1, name: 'Sarah Mitchell', email: 'sarah.m@email.com', avatar: 'SM' },
  { id: 2, name: 'Mike Rodriguez', email: 'mike.r@email.com', avatar: 'MR' },
  { id: 3, name: 'Jennifer Thompson', email: 'jen.t@email.com', avatar: 'JT' },
  { id: 4, name: 'David Chen', email: 'david.c@email.com', avatar: 'DC' },
  { id: 5, name: 'Emma Williams', email: 'emma.w@email.com', avatar: 'EW' }
];

const EXERCISE_DATABASE = [
  { id: 1, name: 'Barbell Bench Press', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Intermediate' },
  { id: 2, name: 'Incline Barbell Bench Press', category: 'Chest', muscleGroup: 'Upper Pectorals', difficulty: 'Intermediate' },
  { id: 3, name: 'Decline Barbell Bench Press', category: 'Chest', muscleGroup: 'Lower Pectorals', difficulty: 'Intermediate' },
  { id: 4, name: 'Dumbbell Bench Press', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Beginner' },
  { id: 5, name: 'Incline Dumbbell Press', category: 'Chest', muscleGroup: 'Upper Pectorals', difficulty: 'Beginner' },
  { id: 6, name: 'Decline Dumbbell Press', category: 'Chest', muscleGroup: 'Lower Pectorals', difficulty: 'Beginner' },
  { id: 7, name: 'Dumbbell Flyes', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Intermediate' },
  { id: 8, name: 'Incline Dumbbell Flyes', category: 'Chest', muscleGroup: 'Upper Pectorals', difficulty: 'Intermediate' },
  { id: 9, name: 'Cable Crossover', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Intermediate' },
  { id: 10, name: 'Chest Dips', category: 'Chest', muscleGroup: 'Lower Pectorals', difficulty: 'Advanced' },
  { id: 11, name: 'Push-ups', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Beginner' },
  { id: 12, name: 'Incline Push-ups', category: 'Chest', muscleGroup: 'Lower Pectorals', difficulty: 'Beginner' },
  { id: 13, name: 'Decline Push-ups', category: 'Chest', muscleGroup: 'Upper Pectorals', difficulty: 'Intermediate' },
  { id: 14, name: 'Pec Deck Machine', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Beginner' },
  { id: 15, name: 'Machine Chest Press', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Beginner' },
  { id: 16, name: 'Deadlift', category: 'Back', muscleGroup: 'Lower Back', difficulty: 'Advanced' },
  { id: 17, name: 'Barbell Rows', category: 'Back', muscleGroup: 'Lats', difficulty: 'Intermediate' },
  { id: 18, name: 'T-Bar Rows', category: 'Back', muscleGroup: 'Lats', difficulty: 'Intermediate' },
  { id: 19, name: 'Dumbbell Rows', category: 'Back', muscleGroup: 'Lats', difficulty: 'Beginner' },
  { id: 20, name: 'Seated Cable Rows', category: 'Back', muscleGroup: 'Mid Back', difficulty: 'Beginner' },
  { id: 21, name: 'Pull-ups', category: 'Back', muscleGroup: 'Lats', difficulty: 'Advanced' },
  { id: 22, name: 'Chin-ups', category: 'Back', muscleGroup: 'Lats', difficulty: 'Advanced' },
  { id: 23, name: 'Lat Pulldown', category: 'Back', muscleGroup: 'Lats', difficulty: 'Beginner' },
  { id: 24, name: 'Close-Grip Pulldown', category: 'Back', muscleGroup: 'Lats', difficulty: 'Beginner' },
  { id: 25, name: 'Wide-Grip Pulldown', category: 'Back', muscleGroup: 'Lats', difficulty: 'Beginner' },
  { id: 26, name: 'Face Pulls', category: 'Back', muscleGroup: 'Rear Delts', difficulty: 'Beginner' },
  { id: 27, name: 'Hyperextensions', category: 'Back', muscleGroup: 'Lower Back', difficulty: 'Beginner' },
  { id: 28, name: 'Good Mornings', category: 'Back', muscleGroup: 'Lower Back', difficulty: 'Intermediate' },
  { id: 29, name: 'Shrugs', category: 'Back', muscleGroup: 'Traps', difficulty: 'Beginner' },
  { id: 30, name: 'Reverse Flyes', category: 'Back', muscleGroup: 'Rear Delts', difficulty: 'Beginner' },
  { id: 31, name: 'Barbell Squat', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Intermediate' },
  { id: 32, name: 'Front Squat', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Advanced' },
  { id: 33, name: 'Goblet Squat', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Beginner' },
  { id: 34, name: 'Bulgarian Split Squat', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Intermediate' },
  { id: 35, name: 'Leg Press', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Beginner' },
  { id: 36, name: 'Leg Extensions', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Beginner' },
  { id: 37, name: 'Romanian Deadlift', category: 'Legs', muscleGroup: 'Hamstrings', difficulty: 'Intermediate' },
  { id: 38, name: 'Leg Curls', category: 'Legs', muscleGroup: 'Hamstrings', difficulty: 'Beginner' },
  { id: 39, name: 'Walking Lunges', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Beginner' },
  { id: 40, name: 'Reverse Lunges', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Beginner' },
  { id: 41, name: 'Lateral Lunges', category: 'Legs', muscleGroup: 'Adductors', difficulty: 'Beginner' },
  { id: 42, name: 'Step-ups', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Beginner' },
  { id: 43, name: 'Calf Raises', category: 'Legs', muscleGroup: 'Calves', difficulty: 'Beginner' },
  { id: 44, name: 'Seated Calf Raises', category: 'Legs', muscleGroup: 'Calves', difficulty: 'Beginner' },
  { id: 45, name: 'Hack Squat', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Intermediate' },
  { id: 46, name: 'Overhead Press', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Intermediate' },
  { id: 47, name: 'Dumbbell Shoulder Press', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Beginner' },
  { id: 48, name: 'Arnold Press', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Intermediate' },
  { id: 49, name: 'Lateral Raises', category: 'Shoulders', muscleGroup: 'Side Delts', difficulty: 'Beginner' },
  { id: 50, name: 'Front Raises', category: 'Shoulders', muscleGroup: 'Front Delts', difficulty: 'Beginner' },
  { id: 51, name: 'Rear Delt Flyes', category: 'Shoulders', muscleGroup: 'Rear Delts', difficulty: 'Beginner' },
  { id: 52, name: 'Upright Rows', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Intermediate' },
  { id: 53, name: 'Cable Lateral Raises', category: 'Shoulders', muscleGroup: 'Side Delts', difficulty: 'Beginner' },
  { id: 54, name: 'Machine Shoulder Press', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Beginner' },
  { id: 55, name: 'Pike Push-ups', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Intermediate' },
  { id: 56, name: 'Barbell Curls', category: 'Arms', muscleGroup: 'Biceps', difficulty: 'Beginner' },
  { id: 57, name: 'Dumbbell Curls', category: 'Arms', muscleGroup: 'Biceps', difficulty: 'Beginner' },
  { id: 58, name: 'Hammer Curls', category: 'Arms', muscleGroup: 'Biceps', difficulty: 'Beginner' },
  { id: 59, name: 'Preacher Curls', category: 'Arms', muscleGroup: 'Biceps', difficulty: 'Intermediate' },
  { id: 60, name: 'Cable Curls', category: 'Arms', muscleGroup: 'Biceps', difficulty: 'Beginner' },
  { id: 61, name: 'Concentration Curls', category: 'Arms', muscleGroup: 'Biceps', difficulty: 'Beginner' },
  { id: 62, name: 'Incline Dumbbell Curls', category: 'Arms', muscleGroup: 'Biceps', difficulty: 'Intermediate' },
  { id: 63, name: 'EZ-Bar Curls', category: 'Arms', muscleGroup: 'Biceps', difficulty: 'Beginner' },
  { id: 64, name: 'Reverse Curls', category: 'Arms', muscleGroup: 'Forearms', difficulty: 'Beginner' },
  { id: 65, name: 'Zottman Curls', category: 'Arms', muscleGroup: 'Biceps', difficulty: 'Intermediate' },
  { id: 66, name: 'Tricep Dips', category: 'Arms', muscleGroup: 'Triceps', difficulty: 'Intermediate' },
  { id: 67, name: 'Close-Grip Bench Press', category: 'Arms', muscleGroup: 'Triceps', difficulty: 'Intermediate' },
  { id: 68, name: 'Overhead Tricep Extension', category: 'Arms', muscleGroup: 'Triceps', difficulty: 'Beginner' },
  { id: 69, name: 'Tricep Pushdown', category: 'Arms', muscleGroup: 'Triceps', difficulty: 'Beginner' },
  { id: 70, name: 'Rope Pushdown', category: 'Arms', muscleGroup: 'Triceps', difficulty: 'Beginner' },
  { id: 71, name: 'Skull Crushers', category: 'Arms', muscleGroup: 'Triceps', difficulty: 'Intermediate' },
  { id: 72, name: 'Dumbbell Kickbacks', category: 'Arms', muscleGroup: 'Triceps', difficulty: 'Beginner' },
  { id: 73, name: 'Diamond Push-ups', category: 'Arms', muscleGroup: 'Triceps', difficulty: 'Intermediate' },
  { id: 74, name: 'Bench Dips', category: 'Arms', muscleGroup: 'Triceps', difficulty: 'Beginner' },
  { id: 75, name: 'Cable Overhead Extension', category: 'Arms', muscleGroup: 'Triceps', difficulty: 'Beginner' },
  { id: 76, name: 'Plank', category: 'Core', muscleGroup: 'Abs', difficulty: 'Beginner' },
  { id: 77, name: 'Side Plank', category: 'Core', muscleGroup: 'Obliques', difficulty: 'Beginner' },
  { id: 78, name: 'Crunches', category: 'Core', muscleGroup: 'Abs', difficulty: 'Beginner' },
  { id: 79, name: 'Bicycle Crunches', category: 'Core', muscleGroup: 'Abs', difficulty: 'Beginner' },
  { id: 80, name: 'Russian Twists', category: 'Core', muscleGroup: 'Obliques', difficulty: 'Beginner' },
  { id: 81, name: 'Hanging Leg Raises', category: 'Core', muscleGroup: 'Lower Abs', difficulty: 'Advanced' },
  { id: 82, name: 'Cable Crunches', category: 'Core', muscleGroup: 'Abs', difficulty: 'Intermediate' },
  { id: 83, name: 'Ab Wheel Rollout', category: 'Core', muscleGroup: 'Abs', difficulty: 'Advanced' },
  { id: 84, name: 'Mountain Climbers', category: 'Core', muscleGroup: 'Abs', difficulty: 'Intermediate' },
  { id: 85, name: 'Dead Bug', category: 'Core', muscleGroup: 'Abs', difficulty: 'Beginner' },
  { id: 86, name: 'Clean and Press', category: 'Full Body', muscleGroup: 'Full Body', difficulty: 'Advanced' },
  { id: 87, name: 'Thrusters', category: 'Full Body', muscleGroup: 'Full Body', difficulty: 'Intermediate' },
  { id: 88, name: 'Burpees', category: 'Full Body', muscleGroup: 'Full Body', difficulty: 'Intermediate' },
  { id: 89, name: 'Box Jumps', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Intermediate' },
  { id: 90, name: 'Kettlebell Swings', category: 'Full Body', muscleGroup: 'Posterior Chain', difficulty: 'Intermediate' },
  { id: 91, name: 'Wrist Curls', category: 'Arms', muscleGroup: 'Forearms', difficulty: 'Beginner' },
  { id: 92, name: 'Reverse Wrist Curls', category: 'Arms', muscleGroup: 'Forearms', difficulty: 'Beginner' },
  { id: 93, name: 'Hip Thrusts', category: 'Legs', muscleGroup: 'Glutes', difficulty: 'Beginner' },
  { id: 94, name: 'Glute Bridges', category: 'Legs', muscleGroup: 'Glutes', difficulty: 'Beginner' },
  { id: 95, name: 'Hip Abduction Machine', category: 'Legs', muscleGroup: 'Glutes', difficulty: 'Beginner' },
  { id: 96, name: 'Hip Adduction Machine', category: 'Legs', muscleGroup: 'Adductors', difficulty: 'Beginner' },
  { id: 97, name: 'Farmer Carries', category: 'Full Body', muscleGroup: 'Grip and Core', difficulty: 'Beginner' },
  { id: 98, name: 'Turkish Get-ups', category: 'Full Body', muscleGroup: 'Full Body', difficulty: 'Advanced' },
  { id: 99, name: 'Landmine Press', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Intermediate' },
  { id: 100, name: 'Landmine Rows', category: 'Back', muscleGroup: 'Lats', difficulty: 'Intermediate' },
  // Add remaining 50 exercises...
  { id: 101, name: 'Wide-Grip Bench Press', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Intermediate' },
  { id: 102, name: 'Close-Grip Dumbbell Press', category: 'Chest', muscleGroup: 'Inner Pectorals', difficulty: 'Intermediate' },
  { id: 103, name: 'Svend Press', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Beginner' },
  { id: 104, name: 'Floor Press', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Intermediate' },
  { id: 105, name: 'Plate Press', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Beginner' },
  { id: 106, name: 'Single-Arm Dumbbell Row', category: 'Back', muscleGroup: 'Lats', difficulty: 'Beginner' },
  { id: 107, name: 'Chest-Supported Row', category: 'Back', muscleGroup: 'Lats', difficulty: 'Beginner' },
  { id: 108, name: 'Meadows Row', category: 'Back', muscleGroup: 'Lats', difficulty: 'Advanced' },
  { id: 109, name: 'Inverted Rows', category: 'Back', muscleGroup: 'Lats', difficulty: 'Intermediate' },
  { id: 110, name: 'Straight-Arm Pulldown', category: 'Back', muscleGroup: 'Lats', difficulty: 'Intermediate' },
  { id: 111, name: 'Sumo Deadlift', category: 'Legs', muscleGroup: 'Hamstrings', difficulty: 'Advanced' },
  { id: 112, name: 'Trap Bar Deadlift', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Intermediate' },
  { id: 113, name: 'Single-Leg Press', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Intermediate' },
  { id: 114, name: 'Sissy Squats', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Advanced' },
  { id: 115, name: 'Nordic Hamstring Curls', category: 'Legs', muscleGroup: 'Hamstrings', difficulty: 'Advanced' },
  { id: 116, name: 'Seated Dumbbell Press', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Beginner' },
  { id: 117, name: 'Standing Barbell Press', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Intermediate' },
  { id: 118, name: 'Behind-the-Neck Press', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Advanced' },
  { id: 119, name: 'Bradford Press', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Intermediate' },
  { id: 120, name: 'Bus Drivers', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Intermediate' },
  { id: 121, name: 'Pallof Press', category: 'Core', muscleGroup: 'Obliques', difficulty: 'Intermediate' },
  { id: 122, name: 'Woodchoppers', category: 'Core', muscleGroup: 'Obliques', difficulty: 'Beginner' },
  { id: 123, name: 'Leg Raises', category: 'Core', muscleGroup: 'Lower Abs', difficulty: 'Intermediate' },
  { id: 124, name: 'Decline Sit-ups', category: 'Core', muscleGroup: 'Abs', difficulty: 'Intermediate' },
  { id: 125, name: 'V-ups', category: 'Core', muscleGroup: 'Abs', difficulty: 'Advanced' },
  { id: 126, name: 'Medicine Ball Slams', category: 'Full Body', muscleGroup: 'Full Body', difficulty: 'Beginner' },
  { id: 127, name: 'Battle Ropes', category: 'Full Body', muscleGroup: 'Full Body', difficulty: 'Intermediate' },
  { id: 128, name: 'Sled Push', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Intermediate' },
  { id: 129, name: 'Sled Pull', category: 'Legs', muscleGroup: 'Hamstrings', difficulty: 'Intermediate' },
  { id: 130, name: 'Prowler Push', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Advanced' },
  { id: 131, name: 'Jump Squats', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Intermediate' },
  { id: 132, name: 'Broad Jumps', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Intermediate' },
  { id: 133, name: 'Depth Jumps', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Advanced' },
  { id: 134, name: 'Plyo Push-ups', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Advanced' },
  { id: 135, name: 'Clapping Push-ups', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Advanced' },
  { id: 136, name: 'Cat-Cow Stretch', category: 'Mobility', muscleGroup: 'Spine', difficulty: 'Beginner' },
  { id: 137, name: 'World Greatest Stretch', category: 'Mobility', muscleGroup: 'Full Body', difficulty: 'Beginner' },
  { id: 138, name: 'Shoulder Dislocations', category: 'Mobility', muscleGroup: 'Shoulders', difficulty: 'Beginner' },
  { id: 139, name: 'Band Pull-Aparts', category: 'Mobility', muscleGroup: 'Shoulders', difficulty: 'Beginner' },
  { id: 140, name: 'Arm Circles', category: 'Mobility', muscleGroup: 'Shoulders', difficulty: 'Beginner' },
  { id: 141, name: 'Pistol Squats', category: 'Legs', muscleGroup: 'Quads', difficulty: 'Advanced' },
  { id: 142, name: 'Archer Push-ups', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Advanced' },
  { id: 143, name: 'One-Arm Dumbbell Snatch', category: 'Full Body', muscleGroup: 'Full Body', difficulty: 'Advanced' },
  { id: 144, name: 'Dragon Flags', category: 'Core', muscleGroup: 'Abs', difficulty: 'Advanced' },
  { id: 145, name: 'L-Sit', category: 'Core', muscleGroup: 'Abs', difficulty: 'Advanced' },
  { id: 146, name: 'Handstand Push-ups', category: 'Shoulders', muscleGroup: 'Deltoids', difficulty: 'Advanced' },
  { id: 147, name: 'Muscle-ups', category: 'Full Body', muscleGroup: 'Full Body', difficulty: 'Advanced' },
  { id: 148, name: 'Ring Dips', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Advanced' },
  { id: 149, name: 'TRX Rows', category: 'Back', muscleGroup: 'Lats', difficulty: 'Intermediate' },
  { id: 150, name: 'TRX Push-ups', category: 'Chest', muscleGroup: 'Pectorals', difficulty: 'Intermediate' },
];

const PRESET_WORKOUTS = [
  {
    id: 'preset-1',
    name: 'Chest Day - High Weight Low Rep',
    exercises: [
      { ...EXERCISE_DATABASE[139], sets: 2, reps: 20, rest: 30, uniqueId: 1001 },
      { ...EXERCISE_DATABASE[138], sets: 2, reps: 15, rest: 30, uniqueId: 1002 },
      { ...EXERCISE_DATABASE[10], sets: 2, reps: 10, rest: 30, uniqueId: 1003 },
      { ...EXERCISE_DATABASE[0], sets: 4, reps: 5, rest: 180, uniqueId: 1004 },
      { ...EXERCISE_DATABASE[1], sets: 4, reps: 6, rest: 150, uniqueId: 1005 },
      { ...EXERCISE_DATABASE[3], sets: 3, reps: 8, rest: 120, uniqueId: 1006 },
      { ...EXERCISE_DATABASE[9], sets: 3, reps: 8, rest: 120, uniqueId: 1007 },
      { ...EXERCISE_DATABASE[8], sets: 3, reps: 15, rest: 60, uniqueId: 1008 },
      { ...EXERCISE_DATABASE[6], sets: 3, reps: 12, rest: 60, uniqueId: 1009 },
      { ...EXERCISE_DATABASE[13], sets: 2, reps: 20, rest: 45, uniqueId: 1010 },
    ]
  },
  {
    id: 'preset-2',
    name: 'Chest Day - Light Weight High Rep',
    exercises: [
      { ...EXERCISE_DATABASE[139], sets: 2, reps: 20, rest: 30, uniqueId: 2001 },
      { ...EXERCISE_DATABASE[138], sets: 2, reps: 15, rest: 30, uniqueId: 2002 },
      { ...EXERCISE_DATABASE[11], sets: 2, reps: 15, rest: 30, uniqueId: 2003 },
      { ...EXERCISE_DATABASE[3], sets: 4, reps: 15, rest: 60, uniqueId: 2004 },
      { ...EXERCISE_DATABASE[4], sets: 4, reps: 15, rest: 60, uniqueId: 2005 },
      { ...EXERCISE_DATABASE[14], sets: 3, reps: 20, rest: 45, uniqueId: 2006 },
      { ...EXERCISE_DATABASE[8], sets: 3, reps: 20, rest: 45, uniqueId: 2007 },
      { ...EXERCISE_DATABASE[6], sets: 3, reps: 20, rest: 45, uniqueId: 2008 },
      { ...EXERCISE_DATABASE[13], sets: 3, reps: 25, rest: 45, uniqueId: 2009 },
      { ...EXERCISE_DATABASE[10], sets: 3, reps: 20, rest: 60, uniqueId: 2010 },
    ]
  },
];

// Copy the rest of the component code from the artifact
// I'll continue with a truncated version due to length...

export default function App() {
  // ... rest of the App component code from the artifact
  return <div>App content here</div>;
}
